- Description: End-effector orientation
  Parameters:
    - ip: 127.0.0.1
      port: 23000
      jointnames: ["/Franka/joint","/Franka/link2_resp/joint","/Franka/link3_resp/joint",
                 "/Franka/link4_resp/joint","/Franka/link5_resp/joint","/Franka/link6_resp/joint",
                 "/Franka/link7_resp/joint"]
      q_min: [-2.3093,-1.5133,-2.4937, -2.7478,-2.4800, 0.8521, -2.6895]
      q_max: [ 2.3093, 1.5133, 2.4937, -0.4461, 2.4800, 4.2094,  2.6895]
      q_dot_min: [-2.62, -2.62, -2.62, -2.62, -5.26, -4.18, -5.26]
      q_dot_max: [ 2.62, 2.62, 2.62, 2.62, 5.26, 4.18, 5.26]
      
      
