- Description: End-effector orientation
  Parameters:
    - ip: 127.0.0.1
      port: 19997
      jointnames: ["Franka_joint1", "Franka_joint2", "Franka_joint3", "Franka_joint4",
               "Franka_joint5", "Franka_joint6", "Franka_joint7"]
      q_min: [-2.3093,-1.5133,-2.4937, -2.7478,-2.4800, 0.8521, -2.6895]
      q_max: [ 2.3093, 1.5133, 2.4937, -0.4461, 2.4800, 4.2094,  2.6895]

